### ISSUE TITLE
Your code is inferior to mine

### ISSUE THREAD

**Issue by Zipdox** [svsdval/video2midi#10]
Mine runs faster than realtime: https://github.com/Zipdox/piano-video-to-midi

**Comment by svsdval** [comment]
Perhaps my code is slower than your, But:
1. main reason for slow performance is using of OpenCV, for getting frame image. But this is used for future plans when i'll try to use deep learning for automatically reconstruction ;)
2. functionality ans usability of my app greater than yours ;)

In first time i also used ffmpeg & PIL to get frames from video, but it requires python 3.5+ (my app works with python 2.7 and above) , and not convenient as using OpenCV. I also planned to add webcam support as input stream, but this is not demanded functionality, so i refused to implement of this functionality ;)

So... yup,  in some case your code faster than mine ;)

I'm glad to see another developer with same interests, We can talk if you want  ;)

**Comment by Zipdox** [comment]
I updated a lot of stuff and added instructions. Made a demo video as well.

**Comment by svsdval** [comment]
GH already added new discuss functionality so we can talk without opening an issue ;) if you have any questions or comments and if you don't mind ;)
