### ISSUE TITLE
merging two notes into one

### ISSUE THREAD

**Issue by catvasily** [svsdval/video2midi#12]
Hello. Thank you for such a wonderful toolbox!
In general, it works great!

I tried to convert this video [https://www.youtube.com/watch?v=HWu-a4zcXbw](url) into midi.
At some moments, two notes are incorrectly recognized as one - I am attaching a picture wherein you can see your GUI interface and part of Synthesia window (please compare the green notes).
Any suggestions with settings?

Also, in the GUI interface, I have "note duration (sec): 10", although the ini file has "minimal_note_duration = 0.1".
I can change it in GUI, but in seconds resolution: 0,1,2,3 seconds etc
Thank you again. 
![cannot recognize two notes](https://user-images.githubusercontent.com/39783092/106397271-53c21b80-63c1-11eb-8c92-bce552b7bc9e.jpg)

**Comment by svsdval** [comment]
You need to enable the "use sparks" functionality:
Here is video example how it works on your video content:
https://user-images.githubusercontent.com/6585839/106539560-cef60f80-6530-11eb-9435-4555e4419946.mp4

Here is config & midi:
[Mozart - Turkish March - EASY Piano Tutorial by PlutaX-HWu-a4zcXbw.mkv.config.zip](https://github.com/svsdval/video2midi/files/5908033/Mozart.-.Turkish.March.-.EASY.Piano.Tutorial.by.PlutaX-HWu-a4zcXbw.mkv.config.zip)

**Comment by svsdval** [comment]
about minimal note duration... Yes, this is mistake in description, so actual value divided by 100, so 10 actually = 0.1

**Comment by svsdval** [comment]
Since there are no new messages, I will close this issue
