### ISSUE TITLE
Small videos issues due to window size

### ISSUE THREAD

**Issue by Maboroshy** [svsdval/video2midi#2]
The size of app window is the same as the opened video size, the window is not resizable. When opening small videos, like 360p, that makes the app overlay controls very cluttered. Also it's almost impossible to precisely adjust keyboard postilion due to the resolution of adjustment. I had to manually adjust keys.

Manually overriding the window size by windows manager doesn't resolve the issue.

**Comment by svsdval** [comment]
by default window resized to video resolution, to resize the window use 'R' key, by the default settings window will be resized to 1280x720. if you save settings by pressing F2 key, app create the .ini file where you can set custom ressolution.

**Comment by Maboroshy** [comment]
Thanks! It took some time to get used to the app.
