### ISSUE TITLE
resize app window

### ISSUE THREAD

**Issue by AlexFundorin** [svsdval/video2midi#25]
When trying to process a small resolution, the GUI is unusable. Is there a way to run the app in full screen?

Исходник видео в маленьком разрешении. Можно как-то извратиться, скрыть менюшки и перетащить ноты в нужное место, но, точно попасть практически нереально. 
Минут пять прицеливался, чтобы наложить ровно всю раскладку. Если бы пришлось индивидумально ноты таскать - вряд ли бы справился. https://i.imgur.com/mYNbQa1.png

**Comment by AlexFundorin** [comment]
Также не очень понятно, что делать вот с такими видео, в которых цвета нот постоянно меняются. Отмотал в конец, где клавиатура без нажатий. Раскидал маркеры по местам, чтобы все стали голубыми и маленькими.
После обработки получил кашу. Просьба подсказать на примере этого видео, если возможно, как правиильно настроить v2m для обработки, чтобы на выходе получить адекватный результат. Можно на одном канале ии на 16, это не критично - https://www.youtube.com/watch?v=aUQjKFTah2M

**Comment by AlexFundorin** [comment]
Про хак с сохранением настроек видео и изменением разрешения в ini прочитал в другом тикете.

**Comment by svsdval** [comment]
> When trying to process a small resolution, the GUI is unusable. Is there a way to run the app in full screen?
> Исходник видео в маленьком разрешении. Можно как-то извратиться, скрыть менюшки и перетащить ноты в нужное место, но, точно попасть практически нереально.
> Минут пять прицеливался, чтобы наложить ровно всю раскладку. Если бы пришлось индивидумально ноты таскать - вряд ли бы справился. https://i.imgur.com/mYNbQa1.png
> Про хак с сохранением настроек видео и изменением разрешения в ini прочитал в другом тикете.

Ru:
Для этого есть клавиша R которая изменяет разрешение окна на 1280x720, его достаточно для всех видео роликов, однако если нужно иное разрешение его нужно будет указать в ini файле.
En:
To do this, there is the R key on keyboard, which changes the resolution of window to the 1280x720, it is enough for all video clips, but if you need a different resolution, you will need to specify it in the ini file.


> Также не очень понятно, что делать вот с такими видео, в которых цвета нот постоянно меняются. Отмотал в конец, где клавиатура без нажатий. Раскидал маркеры по местам, чтобы все стали голубыми и маленькими.
> После обработки получил кашу. Просьба подсказать на примере этого видео, если возможно, как правиильно настроить v2m для обработки, чтобы на выходе получить адекватный результат. Можно на одном канале ии на 16, это не критично - https://www.youtube.com/watch?v=aUQjKFTah2M

Ru:
Тут всё достаточно просто можно выбрать все цвета на видео и указать им всем 1 канал и уменьшить дельту между цветами по которой будет считаться нажатие клавиши, либо можно выбрать только несколько основных цветов и указать дельту больше, тогда будут захватываться ими и похожие цвета 

En:
Its all is quite simple here, you can select all the colors on the video and specify 1 channel for all of them and reduce the delta between the colors by which determinate the keystroke. Or you can select only a few primary colors from the video and specify the delta more, then similar colors will be captured by them.

**Comment by AlexFundorin** [comment]
I'm not familiar with deltas. For some reason, when I try to set up the initial layout on some videos, it seems like the white keys aren't recognized as unpressed, until I move a marker to the brighter part of the key. It's possible to do so in the lower octaves, but the ones on the right are plain grey and don't contain any bright parts.
Here you can see that I'm able to make C1 inactive, by dragging it a bit to the left, while dragging C6 to the same position doesn't make any difference. https://i.imgur.com/xzUTCzf.png
This is the source video. He uses some custom keyboard. I think that this is the reason why v2m is unable to properly detect the resting notes, both black and white. https://www.youtube.com/watch?v=MYq_JT7B2D8
BTW, do you have any plans of adding a shortcut for aligning the markers vertically? When dragging them by the hand, it's sometimes hard to align them and, as far as I could understand, the vertical position of a marker is responsible for the beginning of the note, when using markers on piano roll (while the keyboard is covered by the player's hands).

**Comment by svsdval** [comment]
> I'm not familiar with deltas. For some reason, when I try to set up the initial layout on some videos, it seems like the white keys aren't recognized as unpressed, until I move a marker to the brighter part of the key. It's possible to do so in the lower octaves, but the ones on the right are plain grey and don't contain any bright parts.
> Here you can see that I'm able to make C1 inactive, by dragging it a bit to the left, while dragging C6 to the same position doesn't make any difference. https://i.imgur.com/xzUTCzf.png
> This is the source video. He uses some custom keyboard. I think that this is the reason why v2m is unable to properly detect the resting notes, both black and white. https://www.youtube.com/watch?v=MYq_JT7B2D8

On this video the keyboard rendered in 3d, but this is not no matter. On the video the notes shimmer with random colors, so with lighten colors no problem but with darken colors needs less sensisitivty. So I made new feature called 'use percolor sensisitivity' and you'll can set specific sensitivity for each color in "color map" window.

Here is example settings & output for your video:
[ZUTOMAYO-MILABO-MYq_JT7B2D8_output.zip](https://github.com/svsdval/video2midi/files/6845558/ZUTOMAYO-MILABO-MYq_JT7B2D8_output.zip)


> BTW, do you have any plans of adding a shortcut for aligning the markers vertically? When dragging them by hand, it's sometimes hard to align them and, as far as I could understand, the vertical position of a marker is responsible for the beginning of the note, when using markers on piano roll (while the keyboard is covered by the player's hands).

Yes it is, so in future i'll add this function.

**Comment by AlexFundorin** [comment]
Thanks for helping.

Wouldn't it be easier to show/hide the whole interface with a "tab" button press, instead of manually minimizing each imgui window? The same principle is used in Photoshop, for example. By "whole" I mean everything, except key markers.

**Comment by svsdval** [comment]
Ok, i'll add this feature soon ;)

**Comment by AlexFundorin** [comment]
Nice. I feel like one other thing could be improved, in terms of UI. 

Instead of having a help window with hotkeys explanation, won't it be more convenient to have actual onscreen buttons in that window?

Like 
"|<", "<<<", "<<", ">>", ">>>", ">|" 
with a tooltip "Page Up/Down to scroll video, Shift+ Page Up/Down to scrub, Home/End to jump to the start/end of the video".
You can have playback section, marker adjustments section, etc, so that the user can press the actual buttons, occupying the same screen estate as the help windows does now.

A couple of extra hotkeys for nudging selected marker horizontally would also be nice. Sometimes, when I drag a marker with a mouse, it's hard to be precise. Using something like Shift + <- -> arrows might be more convenient.
Just my thoughts.

**Comment by svsdval** [comment]
Ok, I'll think about it;)

**Comment by svsdval** [comment]
> Wouldn't it be easier to show/hide the whole interface with a "tab" button press, instead of manually minimizing each imgui window? The same principle is used in Photoshop, for example. By "whole" I mean everything, except key markers.

Check last patch, this you mean ?

**Comment by AlexFundorin** [comment]
Exactly. You might also want to duplicate that functionality with a fixed button here - https://i.imgur.com/7LDUNH6.png

**Comment by svsdval** [comment]
Ok, i'll add this button.

**Comment by svsdval** [comment]
check last update..

**Comment by AlexFundorin** [comment]
Nice job! This is looking neat. Notes overlap check is also a good feature.

**Comment by svsdval** [comment]
How will the time, i will continue the refactoring of gui & code. So if you have any questions or suggestions, please wrote. And for this issue, issue is actual ? can i close this issue ? ;)

**Comment by AlexFundorin** [comment]
We already solved the issue.  As for the suggestions, everything's fine now.
Of cause, since I'm using a Windows PC, it would be much more convenient to be able to launch the app without using Anaconda, but I understand that this isn't your main goal.
Having proper icons for the buttons and a single, organized window, would be nice. For now, a 1280x720 is unable to fit the whole UI.
What do you think about the set of controls for a selected marker? What I mean by that is when a marker is selected, one could press a button that says "note under the marker is on/off".
Sometimes, when setting the threshold, I'm moving the sensitivity slider to the left and the resting notes are still acting like they were pressed, while the actual presses note has already become undetected. 
Unwanted detection with high threshold - https://i.imgur.com/cPF0TIS.png
Reducing the sensitivity makes the actual pressed notes undetected - https://i.imgur.com/8N2UnLB.png
Only when moving the slider farther to the left, makes the white resting notes undetected - https://i.imgur.com/CDFHdJv.png

**Comment by svsdval** [comment]
You need to enable the percolor sensitivity for this video, the switch button located on "sparks & color settings" window in right bottom corner ;)

**Comment by AlexFundorin** [comment]
Yep. It was enabled. That is a specific issue with a blue color on this video. The one that you added as an example for the "per color" feature.

**Comment by svsdval** [comment]
send me link to the video and your settings file so I can test it ;)

**Comment by AlexFundorin** [comment]
There are really a lot of flaкes on it. I prefer using the keyboard, since there's no vertical alignment for b/w keys, yet.
Video - https://www.dropbox.com/s/4zirxi8sbceycj5/1.mp4?dl=0
Config - https://www.dropbox.com/s/7qq1srwod1nn2cs/1.mp4.ini?dl=0

**Comment by svsdval** [comment]
>> since there's no vertical alignment for b/w keys, yet.
is is milliseconds, so not so matter

**Comment by svsdval** [comment]
So i check your settings,... you nedd to update the lighten blue color, select it on color map then ctrl+left mouse button on the blue color on keyboard ;)

**Comment by svsdval** [comment]
[example.zip](https://github.com/svsdval/video2midi/files/6862684/example.zip)
i, recreate midi, so wors fine, in zip archive , output midi and settnigs, so you can check what are you do doing wrong

**Comment by AlexFundorin** [comment]
Yep. Works almost great. I suspect that some inconsistencies in tempo are happening because of the video frame rate isn't enough to catch the exact timings, which results in somewhat choppy recognition. Am I right?

**Comment by svsdval** [comment]
Yup, in this video 29.97002997002997 frames per second so you have 0,4995005 sec for each frame and keys on keyboard updating with same time interval.. And therefore we have a problem with the inaccuracy of the reconstruction.
If video will be have variable frame rate like available in webm format we will see lags in the reconstructed midi, because in reconstruction time of a notes (start at time line and duration) resolving with static frame rate ;)

**Comment by AlexFundorin** [comment]
Maybe you meant 0,**0**4995005 seconds?
We need a neural network for recognizing velocity, like Melodyne does. Also, hand movement and position. :)

**Comment by svsdval** [comment]
> Maybe you meant 0,**0**4995005 seconds?

Yes it is, but actualy 0,033366667 seconds to frame ;) the above number wrong, i geted from another video ;)

> Also, hand movement and position. :)
I tried neural network for finding the pressed keys but it's took to long time....
