### ISSUE TITLE
What is this error? Please help 🙏 

### ISSUE THREAD

**Issue by TheNilhist** [svsdval/video2midi#26]
![image](https://user-images.githubusercontent.com/59965507/127798343-5e13747a-f7e9-497e-8e33-51eac0d8547a.png)

**Comment by TheNilhist** [comment]
Tried running it in Ubuntu but same error was shown

**Comment by svsdval** [comment]
Try change video file format from webm to mp4 (convert or download from source, for example on YouTube available the mp4 format)

But Looks like you video Driver not installed properly and OpenGL doesn't work,...
So try to download Mesa3D Windows 32/64 bit build from here: https://fdossena.com/?p=mesa/index.frag
Then extract archive to your preferred path of Python or Anaconda 32 bit, for example like this: C:\ProgramData\Anaconda3\opengl32.dll or C:\Users\User name\AppData\Local\Programs\Python\Python38-32\  or put near v2m.exe
If dosn't help, try replace the system's OpenGL library opengl32.dll in directory C:/Windows/System32 (but it last bad idea)... it will work until you need original hardware accelerated OpenGL ( for example when you change your videocard or sucsessfull installed drivers for your videocard ) ... so be careful ...

**Comment by TheNilhist** [comment]
Yeah after I changed the file format to mp4 it started working
Thanks!!
