### ISSUE TITLE
Bulk notes in some midi conversion

### ISSUE THREAD

**Issue by alexmisailabun** [svsdval/video2midi#29]
Hi,
When I convert some songs, when I open the midi on "midieditor" the right hand notes appear as bulk notes on the beggining, can you help me please? 
SCREENSHOT: https://i.snipboard.io/KQjgkh.jpg

SONG FROM THE SCREENSHOT: https://www.youtube.com/watch?v=ZCut6N52_qY

Thank you.

**Comment by svsdval** [comment]
Hm,look like this is happened because you not setup start point/frame. So You need to set the start point, on keyboard the 'S' key or press the button "set start frame"

**Comment by svsdval** [comment]
Looks like this thread has been abandoned ? Can i close ?
