### ISSUE TITLE
can't find v2m.py

### ISSUE THREAD

**Issue by Okdak-Sempai** [svsdval/video2midi#3]
I'm on linux and after installing it with the command it can't be launched and i can't even find it on my computer

**Comment by svsdval** [comment]
How you installed ?

try:
find / -name v2m.py

**Comment by Okdak-Sempai** [comment]
with this :
sudo apt install python-opencv python-pygame python-midiutil python-opengl
and the command give me mothing aside denied permision
I tried find and locate it five me nothing and it's unbuntu lts

**Comment by Okdak-Sempai** [comment]
I tried with the v2m.py on the code by downloading it to see if it could be used as it but it can't find module with the v2m.py that i downlaoded here

**Comment by svsdval** [comment]
I took some screenshots with the installation process. Tomorrow I will update the linux instruction with these screenshots:
[installation_ubuntu_example.zip](https://github.com/svsdval/video2midi/files/4073095/installation_ubuntu_example.zip)

**Comment by Okdak-Sempai** [comment]
I always get the same error from the v2m.py[](url)
![Screenshot from 2020-01-16 19-56-21](https://user-images.githubusercontent.com/59941239/72554152-6b079700-389a-11ea-9ad8-c9c43db8e2a9.png)

**Comment by Okdak-Sempai** [comment]
I installed all the module by hand it works fine now thank you very much
