### ISSUE TITLE
Проблема с отслеживанием временных промежутков между нажатиями

### ISSUE THREAD

**Issue by FiftyFour7250** [svsdval/video2midi#32]
Привет. Первый раз использую, и результат не очень вышел.

Вот фрагмент оригинального видео
https://disk.yandex.ru/i/W6HIfQbZzvC6-w

А вот этот же момент из получившегося миди
https://disk.yandex.ru/i/kdZAqZ6o8wTr8w

На слух слышно, что там постоянно сбивы какие-то между переходами BC и AG. Глянул в midi редакторе, а там одно нажатие на другое почти наслаиваются, то есть по таймингам не очень точно отслеживается, когда одну клавишу отпустили, и нажимают уже другую. 

![image](https://user-images.githubusercontent.com/78786088/222537291-82e7ba34-acf1-445b-b721-a84657a0b84b.png)

Это я что-то неправильно настроил, или просто Synthesia так отображает нажатия с задержкой, и соответственно твой софт так считывает? В общем, можно ли с этим что-нибудь сделать?

Оригинальный ролик:
https://youtu.be/lvppVNysQeY

**Comment by svsdval** [comment]
Данная программа была сделана для быстрого получения миди из видео, следовательно, от качества ролика и конкретного подхода в настройках при воссоздании зависит и качество получаемого миди файла, потому полученный midi будет требовать пост обработки в большей или меньшей степени исходя из исходных данных видео ролика. 

В текущем же случае софт правильно отрабатывает, в этом можно убедиться самому, что в этом видео ролике так отображается информация о нажатии клавиш. К примеру, поставь 25 секунду в ролике, выстави скорость воспроизведения на 0.25 и обрати внимание как эти клавиши там отображаются и увидишь что отображается они именно, так как у тебя и воссоздаётся. Судя по всему данная мелодия была записана напрямую с игры и из-за этого как человек играл так и записалось, а синтезия при отображении нот квантование использует, но при проигрывании использует данные как есть, отсюда расхождение. Хотя я встречал и такое что в видео ролике идёт одно, а вот звуковая дорожка совершенно иная, иногда доходило до абсурда.

В данном случае, я могу порекомендовать попробовать использовать квантование в редакторе это должно исправить ситуацию. Так же рекомендую в будущем использовать формат mp4, так как там постоянную частоту кадров, а не плавающую. Естественно чем выше FPS в исходном файле тем лучше.

**Comment by svsdval** [comment]
В общем я добавил функцию, которая поможет исправлять эту ситуацию. Включается через кнопку: "sync notes". Если дельта между началам одной ноты и началом другой ноты будет в пределах заданного интервала в мс, то они будут синхронизированы. Это поможет в данной ситуации. Предлагаю обновиться и проверить.
