### ISSUE TITLE
Distorted sound, wrong notes, spamming

### ISSUE THREAD

**Issue by YesIkr** [svsdval/video2midi#34]
Idk why it does this but after I create the midi, the sound of the midi is very distorted and very wrong, Idk if its the amount of keys, the hands or any detail in the video, but I hope anyone can help, here's the link for the video I'm trying to make a midi https://www.youtube.com/watch?v=e0r2vRkKqd4

heres what the midi sounds like after

https://user-images.githubusercontent.com/129657331/229467514-6fd51647-1460-498b-8438-f69bb23512bd.mp4

**Comment by svsdval** [comment]
Hm, very strange music, but if you need here is the output midi, and some edit will need to clean up.
[midi.zip](https://github.com/svsdval/video2midi/files/11139682/midi.zip)

**Comment by YesIkr** [comment]
do you have an example for when the piano has more notes than usual?, I do
it to this one https://youtu.be/-D8jyrtADFQ, THANK YOU AGAIN

**Comment by svsdval** [comment]
Checkout last update ;)
![image](https://user-images.githubusercontent.com/6585839/229981526-fcd69489-f9e3-45a8-b185-c9e5dcfb118c.png)
Here is output
https://drive.google.com/file/d/1DgdFfUIZbVdhI8OM_-QslbYwmsOeTSg2/view?usp=share_link

**Comment by YesIkr** [comment]
Hi! I was wondering if you could help me with this?
https://www.youtube.com/watch?v=v7vKsw_T1dA I'm really struggling on it, I
cant make it as I want it to sound, I hope you can help

**Comment by svsdval** [comment]
Here is output:
[Piano Sonata No.2  -Excerpt- [Mamoru Samuragochi,Takashi Nigaki] [v7vKsw_T1dA].zip](https://github.com/svsdval/video2midi/files/11199602/Piano.Sonata.No.2.-Excerpt-.Mamoru.Samuragochi.Takashi.Nigaki.v7vKsw_T1dA.zip)
