### ISSUE TITLE
Oversized window

### ISSUE THREAD

**Issue by DawidPrz** [svsdval/video2midi#35]
Facing issues with oversized window. The resize window button does not help. 
For instance, color map is always cropped.
System Windows 10, screen display resolution 1920x1080. I use fullhd screen notebook and a external display also fullhd. Even if I use only the notebook screen, the issue persists. Any ideas?

![oversized window](https://user-images.githubusercontent.com/113210727/232315852-a8ea0692-285e-4836-9aea-5b17bb274f8d.jpg)

**Comment by svsdval** [comment]
Hm, try to save settings, and find the .ini file named as your video file, then open it in any text file editor and change these parameters:
resize to 1 resize_width and resize_height to needed resolution.
Then load changed settings.

For example:
resize = 1
resize_width = 1024
resize_height = 576

**Comment by svsdval** [comment]
Checkout last update, try press F4 to move all windows to the mouse point.
and also tell me your system information, version for the Windows and video drivers

**Comment by svsdval** [comment]
Checkout last update, i added auto fit to the screen and window resize...
