### ISSUE TITLE
Better Arch Linux instructions

### ISSUE THREAD

**Issue by C0rn3j** [svsdval/video2midi#36]
opencv dep should be changed to python-opencv, as that one is missing and it includes opencv as a bonus.

Better yet, I have packaged both midiutil and this repo, one can just install from AUR now - https://aur.archlinux.org/packages/video2midi-git

**Comment by svsdval** [comment]
I updated the readme by adding an extra quick way to install video2midi with your package for Arch GNU/Linux ;)
