### ISSUE TITLE
Crashing or doesnt work

### ISSUE THREAD

**Issue by IzQuicksI** [svsdval/video2midi#39]
Hello, someone suggested your video to me because I love Virtual Piano more than anything and I need Sheets. These videos they showed me shows me that I need to download Video2midi in Github. I have now done this and went to the ornder Docs. Since I have Windows 10, I selected the folder Win_Install and did all the steps except the last, because there is an error. I tried it anyway then. I downloaded the Youtube video on MP4 then pressed V2m and then selected the video it was selected and neither the video nor the function opens. heres the Video what Ima sent you what is happening: https://youtu.be/a6tJ0NKQJ2k

**Comment by IzQuicksI** [comment]
Would be great if you do an full step of these xD
Dont understand that so well tho

**Comment by C0rn3j** [comment]
> there is an error

Post the error in full then.

> YouTube video

That's set to private

**Comment by IzQuicksI** [comment]
At Anaconda Prompt I Wrote C:/video2midi-master It worked at first. then I wrote(base) C:\video2midi-master>python ./v2m.oy "Oceans - Hillsong United - Tutorial Piano Cover.mp4" and the data cant get find hmm issue XD

**Comment by svsdval** [comment]
1. This video is private/closed, so I don't see what the problem is.

> (base) c:\video2midi-master>python ./v2m.oy "Oceans - Hillsong United - Tutorial Piano Cover.mp4
2. Try run: python v2m.py, not oy. You can run v2m.py without song name, so the Open File Dialog will be shown.
3. Attach your screenshots of your problem so we can see it and help you solve it.

**Comment by IzQuicksI** [comment]
Here the Issue https://youtu.be/a6tJ0NKQJ2k

**Comment by svsdval** [comment]
Need run in command prompt mode to see error. Or python ./v2m.py 2>stderr.txt 1>stdout.txt
