### ISSUE TITLE
Lack of quantization option leads to weird rhythms

### ISSUE THREAD

**Issue by RyantheKing** [svsdval/video2midi#4]
First off, I think this is a good tool, and is the only thing I could find to do the job I wanted, and for being a one-man project, it is near perfect.  My main complaint is that the rhythm always turns out a little weird.  This could be fixed by having the program count notes at proper intervals.  For instance, I would set time to frame 1, note the bpm of the song, and then tell it the smallest interval in the song.  This would likely be a quick edit that could be made to the song after the midi is generated.  Although I'm not a midi expert, I feel this could fix some rhythm problems.

**Comment by svsdval** [comment]
Try to change video format for example to mp4, because OpenCV has errors with it... Some video formats can have 'lags' when OpenCV get image while converting to midi... I think, this is OpenCV bug.
To control output BPM you can change slider "Output tempo".

**Comment by svsdval** [comment]
Can I close issue ?

**Comment by RyantheKing** [comment]
Yeah, we are talking about separate things, but I figured out a way to fix it and its a lot easier to fix on user end than in the code.
