### ISSUE TITLE
Не очень понятно, как вывести подряд идущие..

### ISSUE THREAD

**Issue by Access-deny** [svsdval/video2midi#42]
Здравствуйте! Отличная идея. Но чего-то не получается - все подряд идущие ноты сливает в одну, игнорирует очень короткие ноты.
Пример видео: https://www.youtube.com/watch?v=zatW6ZVR6DE
Midi там есть, так что можно сравнить.

**Comment by svsdval** [comment]
Вообще для этого есть функционал искр, который это дело должен исправлять.
