### ISSUE TITLE
How to add colors - Как добавить цвета

### ISSUE THREAD

**Issue by GXboy12345** [svsdval/video2midi#43]
Hey, I have a few videos that don't have the preset colors, how do I add colors?

TRANSLATION/ПЕРЕВОД:
===========
Привет, у меня есть несколько видео, в которых нет предустановленных цветов. Как мне добавить цвета?

**Comment by svsdval** [comment]
https://github.com/svsdval/video2midi/wiki/First-steps,-or-How-to-use-after-installing#step-2-you-need-to-set-up-the-used-colors-on-color-map-window
