### ISSUE TITLE
Very glitchy midi

### ISSUE THREAD

**Issue by worda3** [svsdval/video2midi#46]
Hello whenever i recreate the midi the video playback glitches and when it finishes, the midi is very glitchy for some reason.

Here is the video showcasing it: https://www.youtube.com/watch?v=Vm1x1yw19uc
This is the video i am trying to get a midi of: https://www.youtube.com/watch?v=5HgExMvlERg

What the midi sounds like:

https://github.com/svsdval/video2midi/assets/154682138/83007278-a6ae-4634-bbdc-e86097c63379

This is the start and end of the log if that helps idk

![Screenshot 2023-12-23 135309](https://github.com/svsdval/video2midi/assets/154682138/44495379-0cd7-43f6-b981-8f0c26a3f529)
![Screenshot 2023-12-23 135341](https://github.com/svsdval/video2midi/assets/154682138/c93e889b-bf26-48ea-8bd6-97d0b9865238)

Everything was installed properly and it does this with every song i try to do.

**Comment by svsdval** [comment]
Looks like your video driver not works well but this isn't problem in your midi glitch, your midi glitch connected to spark noise in video, your keys line to low and "sparks" was in check area. Here is a config and midi for this video ;)
[Joji - Glimpse of Us ｜ Piano Cover by Pianella Piano [5HgExMvlERg]_witout_video.zip](https://github.com/svsdval/video2midi/files/13762266/Joji.-.Glimpse.of.Us.Piano.Cover.by.Pianella.Piano.5HgExMvlERg._witout_video.zip)

**Comment by worda3** [comment]
How do I get my video driver to work well with it? I have an rtx 3070 and have latest version of all the drivers.

**Comment by svsdval** [comment]
> How do I get my video driver to work well with it? I have an rtx 3070 and have latest version of all the drivers.
Hm, you have this issue on latest drivers ?
Tell me your windows and GPU drivers version

**Comment by worda3** [comment]
I have version 546.33 of geforce experience which says it is the latest

**Comment by svsdval** [comment]
Checkout the last patch of the video2midi

**Comment by worda3** [comment]
Oh ok, yeah it works now thanks a lot!
