### ISSUE TITLE
curious to know if it could be run in colab notebook ?

### ISSUE THREAD

**Issue by timtensor** [svsdval/video2midi#48]
Hi, the youtube vidoes and the instructions look really good. Is it possible to run it on a colab environment ?

**Comment by svsdval** [comment]
i dont thinks so, i think colab environment doesn't work with OpenCV and OpenGL in real time, so you can't manipulate with piano keys and other settings. But if save settings to file (in app by pressing f2 key or save settings button) and slightly change some code (to load settings and run reconstruction) the reconstruction code will be work fine, and you will get your midi file.
