### ISSUE TITLE
Installation in MacOS

### ISSUE THREAD

**Issue by matteosecli** [svsdval/video2midi#5]
Just here to confirm that the program works in MacOS as well. To install the dependencies, one can just use pip (as already documented for Linux in the Wiki):

```bash
pip install opencv-python pygame midiutil pyopengl
```

Tested on MacOS 10.14.6, Python 3.7.7 (installed via Homebrew), pip 20.0.2.

Maybe could there be a suggestion in the README to install the dependencies via pip for MacOS installations.

**Comment by svsdval** [comment]
Thanks a lot, could you create manual with images to MacOS users ?

**Comment by matteosecli** [comment]
I've shot some screenshots and I've put them in this archive: [macos_steps_001-007.zip](https://github.com/svsdval/video2midi/files/4422094/macos_steps_001-007.zip). Does it work for you?

Unfortunately I could not *actually* run all the commands since I don't have a clean installation and most of the things are already installed on my machine. However, from step 3 (included) onwards is exactly what I did to make the software run on my machine (since I already had Homebrew and Python installed).

I've also found that 720p is a reasonable resolution to work with, because unfortunately v2m's window is not resizable (at least on MacOS), so e.g. the window of a 1080p video does not fit completely into my screen and gets cropped.

This is the preview of the images in the archive, together with the steps:

- **Step 1**
  Install [Homebrew](https://brew.sh):
  ```bash
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  ```
  <img width="1082" alt="macos_step_001" src="https://user-images.githubusercontent.com/4618521/78269944-833a9a00-750a-11ea-903f-382f35845c3a.png">
- **Step 2**
  Install Python 3 via Homebrew:
  ```bash
  brew install python
  ```
  <img width="1082" alt="macos_step_002" src="https://user-images.githubusercontent.com/4618521/78269960-8766b780-750a-11ea-95ba-95326492675a.png">
- **Step 3**
  Install video2midi's dependencies via Homebrew's Python:
  ```bash
  pip install opencv-python pygame midiutil pyopengl
  ```
  <img width="1082" alt="macos_step_003" src="https://user-images.githubusercontent.com/4618521/78269967-8897e480-750a-11ea-803c-599c4d3d2b05.png">
- **Step 4**
  Clone [video2midi](https://github.com/svsdval/video2midi)'s git repository:
  ```bash
  git clone https://github.com/svsdval/video2midi.git
  ```
  <img width="1082" alt="macos_step_004" src="https://user-images.githubusercontent.com/4618521/78269970-89c91180-750a-11ea-8196-60b3e7a5706f.png">
- **Step 5**
  Move into video2midi's folder:
  ```bash
  cd video2midi/
  ```
  <img width="1082" alt="macos_step_005" src="https://user-images.githubusercontent.com/4618521/78270589-4de27c00-750b-11ea-8e20-5226854c8ec6.png">
- **Step 6**
  Put your video (say it's called `yourvideo_720p.mp4`, the suggested resolution is 720p) in video2midi's directory and run video2midi as: 
  ```bash
  python v2m.py your video_720p.mp4
  ```
  <img width="1082" alt="macos_step_006" src="https://user-images.githubusercontent.com/4618521/78269978-8b92d500-750a-11ea-94ae-619dbd356fd1.png">
- **Step 7**
  Fine-tune by following the usage instructions and enjoy!
  <img width="1392" alt="macos_step_007" src="https://user-images.githubusercontent.com/4618521/78269986-8c2b6b80-750a-11ea-91df-3b44bcddd6b2.png">

**Comment by svsdval** [comment]
Thanks alot =)

**Comment by matteosecli** [comment]
You're welcome! :smile:

**Comment by svsdval** [comment]
I updated wiki with your instruction:[Using video2midi from github on Mac OS](https://github.com/svsdval/video2midi/wiki/Using-video2midi-from-github-on-Mac-OS)
Again, thanks a lot ;)
