### ISSUE TITLE
При выборе видео происходит ошибка

### ISSUE THREAD

**Issue by ReKuRsKeR** [svsdval/video2midi#50]
(base) C:\Users\Admin\Desktop\video2midi-0.4.8>v2m.py
get file [C:/Users/Admin/Desktop/synthesia_video.mp4]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\video2midi-0.4.8\v2m.py", line 54, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by svsdval** [comment]
У тебя не поставлены зависимости в каталоге с v2m есть файл [requirements.txt](https://github.com/svsdval/video2midi/blob/master/requirements.txt), можно поставить через pip install -r requirements.txt или pip install MIDIUtil opencv-python pygame PyOpenGL
