### ISSUE TITLE
I have difficulty using it

### ISSUE THREAD

**Issue by MapperZ1** [svsdval/video2midi#51]
I want to convert this song [Link] https://www.youtube.com/watch?v=0oZehjofwH0, when I open the midi file the notes are always spam and messy

**Comment by svsdval** [comment]
> /Users/quynh/Repositories/GitHub/video2midi/video2midi/gl.py:242: RuntimeWarning: use font: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/Users/quynh/.pyenv/versions/py39/lib/python3.9/site-packages/pygame/font.py)
> (ImportError: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/Users/quynh/.pyenv/versions/py39/lib/python3.9/site-packages/pygame/font.py))
>   font = pygame.font.Font( None , fontSize )
> Traceback (most recent call last):
>   File "/Users/quynh/Repositories/GitHub/video2midi/v2m.py", line 1687, in <module>
>     main()
>   File "/Users/quynh/Repositories/GitHub/video2midi/v2m.py", line 1419, in main
>     doinit()
>   File "/Users/quynh/Repositories/GitHub/video2midi/v2m.py", line 1375, in doinit
>     GenFontTexture()
>   File "/Users/quynh/Repositories/GitHub/video2midi/video2midi/gl.py", line 242, in GenFontTexture
>     font = pygame.font.Font( None , fontSize )
>   File "/Users/quynh/.pyenv/versions/py39/lib/python3.9/site-packages/pygame/__init__.py", line 59, in __getattr__
>     raise NotImplementedError(missing_msg)
> NotImplementedError: font module not available (ImportError: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/Users/quynh/.pyenv/versions/py39/lib/python3.9/site-packages/pygame/font.py))
> ```

Look like error in pygame, https://stackoverflow.com/questions/68613492/importerror-cannot-import-name-font-from-partially-initialized-module-pygame

**Comment by svsdval** [comment]
> I want to convert this song [Link] https://www.youtube.com/watch?v=0oZehjofwH0, when I open the midi file the notes are always spam and messy

Can you share your saved ini file ?

**Comment by MapperZ1** [comment]
> > I want to convert this song [Link] https://www.youtube.com/watch?v=0oZehjofwH0, when I open the midi file the notes are always spam and messy
> 
> Can you share your saved ini file ?

I did not save the ini file because I reinstalled from scratch. But before that my white keys were not as your instructions, it showed red and received signal from midi video key color, but when exported to midi the keys were messed up

**Comment by svsdval** [comment]
Hmm, this is very strange, this should not happen.

**Comment by svsdval** [comment]
> I want to convert this song [Link] https://www.youtube.com/watch?v=0oZehjofwH0, when I open the midi file the notes are always spam and messy

Checkout last update

**Comment by MapperZ1** [comment]
I will check, thanks for letting me know

**Comment by MapperZ1** [comment]
I will check, thanks for letting me know

**Comment by svsdval** [comment]
[Un Amour Impossible, Pt. 2 ｜ Joshua Kyan Aalampour [0oZehjofwH0].mp4.zip](https://github.com/user-attachments/files/17390858/Un.Amour.Impossible.Pt.2.Joshua.Kyan.Aalampour.0oZehjofwH0.mp4.zip)
Here are the settings and MIDI file I created from your video.

**Comment by MapperZ1** [comment]
> [Un Amour Impossible, Pt. 2 ｜ Joshua Kyan Aalampour [0oZehjofwH0].mp4.zip](https://github.com/user-attachments/files/17390858/Un.Amour.Impossible.Pt.2.Joshua.Kyan.Aalampour.0oZehjofwH0.mp4.zip)
> Here are the settings and MIDI file I created from your video.

Thanks for supporting me

**Comment by MapperZ1** [comment]
> [Un Amour Impossible, Pt. 2 ｜ Joshua Kyan Aalampour [0oZehjofwH0].mp4.zip](https://github.com/user-attachments/files/17390858/Un.Amour.Impossible.Pt.2.Joshua.Kyan.Aalampour.0oZehjofwH0.mp4.zip)
> Here are the settings and MIDI file I created from your video.

Thanks for supporting me
