### ISSUE TITLE
Color recognition inconsistency

### ISSUE THREAD

**Issue by by-nari** [svsdval/video2midi#52]
I tried it on Windows, both the old and new versions of this code no longer work as before with different videos. The situation I encountered is similar to the picture.

Both keys are the same color but one side is recognized and the other side is not.

I am not new to this tool but recently I reinstalled my computer and had to reinstall video2midi but I don't find it working exactly like it used to.

I thought I did something wrong so I tried different versions of python:
- default on macOS 14, 15 installed via xcode command line tools
- various versions on macOS installed via pyenv
- various versions on windows downloaded from python.org
- various versions on windows downloaded from microsoft store

I also made sure I installed the correct libraries according to requirements.txt using venv as virtualenv with command `pip install -r requirements.txt`

Can you setup an environment using pyenv and try using the tool with this song https://www.youtube.com/watch?v=_ByCokkTvCo

If it works please give me the configuration you have set for the environment and the output of the command `pip freeze > requirements.txt`

<img width="2403" alt="368927937-49912e17-238d-4a8a-9fd7-878cea8aacfb" src="https://github.com/user-attachments/assets/6895d7c6-f39a-4dbf-aea5-3c1fdf7322ee">

**Comment by svsdval** [comment]
I'll check everything, I just don't have any macOS, so it's hard for me to check this problem, and there are no virtual machines for the required version of macOS. So, it will take some time...

**Comment by C0rn3j** [comment]
> I'll check everything, I just don't have any macOS, so it's hard for me to check this problem, and there are no virtual machines for the required version of macOS for Virtualbox. So, it will take some time... because I will look for the required version of macOS on the internet & intranet.

OP claims Windows is bust too, so macOS is not necessary.

**Comment by svsdval** [comment]
checkout, here is little fix in /video2midi/gl.py

i replaced single line from
```python
fontChars = u''' !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz><'''
```
to
```python
fontChars = ''' !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz><'''
```
tested on Windows 10 22H2 + Python 3.13.0 + venv
[video2midi-glfix.zip](https://github.com/user-attachments/files/17383066/video2midi-glfix.zip)
