### ISSUE TITLE
Shifting the starting key

### ISSUE THREAD

**Issue by Haano137** [svsdval/video2midi#56]
This is less of an issue and more of a suggestion but I think being able to change the starting key so that we can reach more notes would be great!
![image](https://github.com/user-attachments/assets/1a53b67f-dc88-46c9-be6b-1c7ba15b17af)

**Comment by svsdval** [comment]
Use right mouse button on any key to grab entire keyboard
[Video example](https://drive.google.com/file/d/1KTGzhhDMaDEttK-Zx_zNeNc190X_TZCt/view?usp=sharing)

**Comment by Haano137** [comment]
> Use right mouse button on any key to grab entire keyboard [Video example](https://drive.google.com/file/d/1KTGzhhDMaDEttK-Zx_zNeNc190X_TZCt/view?usp=sharing)

Oh I haven't considered that. Much thanks!
