### ISSUE TITLE
Scanning the notes from the upper side of the piano roll

### ISSUE THREAD

**Issue by phajiyev** [svsdval/video2midi#6]
There are some Synthesia videos on YouTube which does not have Synthesia's standard piano panel on the bottom (replaced with hands (like this one: https://www.youtube.com/watch?v=gQgb0cK0mcs).

It would be great if this program could have an option to read the notes from the upper side of the piano panel as well.

**Comment by svsdval** [comment]
Ok, i will think about this solution ...

**Comment by svsdval** [comment]
I create a two videos for this problem:

Variant 1
Used a experimental functions to read keys...Black keys may not reading and source video quality may create a noise, So some tweaks for note positions and cleaning midi needed... 

https://youtu.be/CF7k9A8Ql7E

Variant 2
All keys on same Y. So when note roll and collide with two keys, some tweaks for note positions and cleaning midi needed... 

https://youtu.be/I0hK43OAszE

**Comment by svsdval** [comment]
Have you tried this solution?

**Comment by phajiyev** [comment]
Hi,

Sorry for the late reply.

I haven't had a chance to try that, but saw the video you have uploaded.
Seems like it will work. Thanks a lot!

**Comment by svsdval** [comment]
If you have any questions or need for change, let me know.
