### ISSUE TITLE
Black key position can be tuned a little bit

### ISSUE THREAD

**Issue by wuzhuoqing** [svsdval/video2midi#8]
Thanks for the great tool. The default location for each black key can be tuned a little bit, like
```
    if (j == 1) or ( j == 6 ):
      keys_pos[i*12+j][0] = int(round( xx  + whitekey_width *0.4 ));
    if (j == 8 ):
      keys_pos[i*12+j][0] = int(round( xx  + whitekey_width *0.5 ));
    if ( j ==3 ) or ( j == 10 ):
      keys_pos[i*12+j][0] = int(round( xx  + whitekey_width *0.6 ));
```

**Comment by svsdval** [comment]
Thanks, can you make pull request ? or can I insert your code with commentary ?

**Comment by wuzhuoqing** [comment]
My local change is too messy for a PR :-(. 
Feel free to do what you want. Again thanks for the great tool.

**Comment by svsdval** [comment]
Thanks ;)

**Comment by svsdval** [comment]
added in release ;)
